### ISSUE TITLE
Word error in Readme.md

### ISSUE THREAD

**Issue by Menghua1** [FBoucher/ZipDeploy-AzFunc#2]
**Describe the issue:**
The word `tempate` below is misspelled.
![image](https://github.com/FBoucher/ZipDeploy-AzFunc/assets/111940661/711a7b35-5aa4-4124-9440-48fe89c6101a)
**Suggestion:**
Update to `template`.

@FBoucher and @hemarina for notification.

**Comment by fboucher** [comment]
Good catch @Menghua1, thank you. It's fixed
